repos:
  - repo: https://github.com/digitalpulp/pre-commit-php.git
    rev: 1.4.0
    hooks:
      - id: php-lint

  - repo: https://github.com/digitalpulp/pre-commit-php.git
    rev: 1.4.0
    hooks:
      - id: php-cs-fixer
        files: \.(php)$

#  - repo: https://github.com/digitalpulp/pre-commit-php.git
#    rev: 1.4.0
#    hooks:
#      - id: php-stan
#        files: \.(php)$

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.1.0
    hooks:
      - id: commitlint
        stages: [ commit-msg ]
        additional_dependencies: [ '@commitlint/config-angular' ]
